# Antes de Empezar

---

In [1]:
# Ejercicio 1
# Suma y Resta de Números Complejos
num1 = 3 + 4j
num2 = 1 - 2j

# Suma
suma = num1 + num2

# Resta
resta = num1 - num2

suma, resta

((4+2j), (2+6j))

In [2]:
# Ejercicio 2
# Resolución de Ecuaciones Lineales
import numpy as np
import warnings

warnings.filterwarnings("ignore")

coeficientes = np.array([[3, 2], [4, -1]])
constantes = np.array([9, 5])

solucion = np.linalg.solve(coeficientes, constantes)
solucion

array([1.72727273, 1.90909091])

In [3]:
# Ejercicio 3
# Factorización de Polinomios Cuadráticos
from sympy import symbols, factor

x = symbols("x")
polinomio = x**2 - 5 * x + 6

factorizado = factor(polinomio)
factorizado

(x - 3)*(x - 2)

In [4]:
# Ejercicio 4
# Operaciones con Matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[5, 6], [7, 8]])

# Multiplicación de Matrices
multiplicación = np.dot(matriz_a, matriz_b)

# Transposición de Matrices
transpuesta_a = matriz_a.T

multiplicación, transpuesta_a

(array([[19, 22],
        [43, 50]]),
 array([[1, 3],
        [2, 4]]))

In [5]:
# Ejercicio 5
# Despejar Variables en Ecuaciones
from sympy import symbols, solve

x, y = symbols("x y")
ecuacion = 2 * x + 3 * y - 12

# Despejar y
solucion_y = solve(ecuacion, "y")
solucion_y

[4 - 2*x/3]

# FIN DEL CAPÍTULO